import type { DepDriftReport } from "./types";

export type FixtureId = "polyglot" | "monorepo" | "python" | "conflict";

export const FIXTURES: { id: FixtureId; label: string; hint: string }[] = [
  { id: "polyglot", label: "Polyglot", hint: "Node + Python" },
  { id: "monorepo", label: "Monorepo", hint: "Node workspaces" },
  { id: "python", label: "Python", hint: "pip / requirements" },
  { id: "conflict", label: "Version Conflict", hint: "cross-package" },
];

const polyglot: DepDriftReport = {
  version: "0.4.0",
  repository: {
    name: "demo-project",
    source: "https://github.com/depdrift/demo-project",
    branch: "main",
    scannedAt: "2026-08-29T09:41:00Z",
    ecosystems: ["node", "python"],
  },
  findings: [
    {
      id: "f-001",
      dependency: "lodash",
      fromPackage: "app",
      ecosystem: "node",
      type: "version_drift",
      severity: "HIGH",
      expectedVersion: "^4.17.0",
      actualVersion: "4.17.21",
      reasoning:
        "The resolved version falls outside the declared dependency range, creating potential breaking-change risk.",
      evidence: ["package.json", "package-lock.json", "packages/app/src/format.ts"],
      introducedCommit: {
        hash: "8f21a9",
        date: "2026-08-29",
        author: "priya@demo",
        message: "chore: bump utility deps",
      },
      suggestedFix: "npm install lodash@4.17.21",
    },
    {
      id: "f-002",
      dependency: "axios",
      fromPackage: "packages/app",
      ecosystem: "node",
      type: "missing_dependency",
      severity: "MEDIUM",
      actualVersion: "not installed",
      reasoning:
        "`axios` is imported at runtime but never declared in the package manifest, so builds succeed only via hoisting.",
      evidence: ["packages/app/src/api/client.ts", "packages/app/package.json"],
      introducedCommit: {
        hash: "c14d70",
        date: "2026-08-21",
        author: "marco@demo",
        message: "feat: add http client",
      },
      suggestedFix: "npm install axios@1.7.4 --workspace packages/app",
    },
    {
      id: "f-003",
      dependency: "numpy",
      fromPackage: "services/ml",
      ecosystem: "python",
      type: "missing_dependency",
      severity: "HIGH",
      actualVersion: "not declared",
      reasoning:
        "`numpy` is imported by main.py but absent from requirements.txt, so a clean environment fails at import time.",
      evidence: ["services/ml/main.py", "services/ml/requirements.txt"],
      introducedCommit: {
        hash: "a90f31",
        date: "2026-08-18",
        author: "lena@demo",
        message: "feat: vectorized scoring",
      },
      suggestedFix: "pip install numpy==2.1.0",
    },
    {
      id: "f-004",
      dependency: "flask",
      fromPackage: "services/ml",
      ecosystem: "python",
      type: "unnecessary_dependency",
      severity: "LOW",
      expectedVersion: "3.0.3",
      actualVersion: "3.0.3",
      reasoning:
        "Declared in requirements.txt but no module in the package imports it — dependency bloat on the runtime image.",
      evidence: ["services/ml/requirements.txt"],
      introducedCommit: {
        hash: "5b0ce2",
        date: "2026-07-30",
        author: "lena@demo",
        message: "chore: scaffold service",
      },
      suggestedFix: "pip uninstall flask && remove from requirements.txt",
    },
    {
      id: "f-005",
      dependency: "urllib3",
      fromPackage: "services/api",
      ecosystem: "python",
      type: "version_drift",
      severity: "HIGH",
      expectedVersion: ">=1.26,<2.0",
      actualVersion: "2.2.2",
      reasoning:
        "Lockfile resolves a major version above the declared constraint; urllib3 2.x removed the legacy retry behaviour used here.",
      evidence: ["services/api/requirements.txt", "services/api/poetry.lock"],
      introducedCommit: {
        hash: "d31b48",
        date: "2026-08-27",
        author: "marco@demo",
        message: "chore: refresh lockfile",
      },
      suggestedFix: "pip install 'urllib3<2.0'",
    },
    {
      id: "f-006",
      dependency: "@demo/utils",
      fromPackage: "packages/app",
      ecosystem: "node",
      type: "missing_dependency",
      severity: "HIGH",
      reasoning:
        "Workspace package imported from the app entrypoint without a workspace dependency entry — breaks isolated builds.",
      evidence: ["packages/app/src/index.ts", "packages/app/package.json"],
      introducedCommit: {
        hash: "77aa12",
        date: "2026-08-12",
        author: "priya@demo",
        message: "refactor: extract utils",
      },
      suggestedFix: 'npm pkg set dependencies.@demo/utils="workspace:*" --workspace packages/app',
    },
    {
      id: "f-007",
      dependency: "lodash",
      fromPackage: "packages/ui",
      ecosystem: "node",
      type: "version_conflict",
      severity: "HIGH",
      expectedVersion: "^4.17.0",
      actualVersion: "^3.0.0",
      reasoning:
        "packages/ui declares lodash ^3.0.0 while packages/app declares ^4.17.0, duplicating the dependency in the bundle.",
      evidence: ["packages/ui/package.json", "packages/app/package.json"],
      introducedCommit: {
        hash: "8f21a9",
        date: "2026-08-29",
        author: "priya@demo",
        message: "chore: bump utility deps",
      },
      suggestedFix: "npm install lodash@^4.17.0 --workspace packages/ui",
    },
    {
      id: "f-008",
      dependency: "requests",
      fromPackage: "services/api",
      ecosystem: "python",
      type: "missing_dependency",
      severity: "MEDIUM",
      reasoning:
        "Imported transitively through urllib3 but never declared; a resolver change would drop it from the environment.",
      evidence: ["services/api/client.py", "services/api/requirements.txt"],
      introducedCommit: {
        hash: "d31b48",
        date: "2026-08-27",
        author: "marco@demo",
      },
      suggestedFix: "pip install requests==2.32.3",
    },
    {
      id: "f-009",
      dependency: "moment",
      fromPackage: "packages/ui",
      ecosystem: "node",
      type: "unnecessary_dependency",
      severity: "LOW",
      actualVersion: "2.30.1",
      reasoning: "No import references moment; 290 kB of unused bundle weight shipped to clients.",
      evidence: ["packages/ui/package.json"],
      introducedCommit: { hash: "1c4e05", date: "2026-06-14", author: "sam@demo" },
      suggestedFix: "npm uninstall moment --workspace packages/ui",
    },
    {
      id: "f-010",
      dependency: "typescript",
      fromPackage: "packages/ui",
      ecosystem: "node",
      type: "version_conflict",
      severity: "MEDIUM",
      expectedVersion: "^5.8.0",
      actualVersion: "^5.4.2",
      reasoning:
        "Two TypeScript versions resolved across the workspace, producing inconsistent type-check results in CI.",
      evidence: ["packages/ui/package.json", "package-lock.json"],
      introducedCommit: { hash: "b62f80", date: "2026-08-05", author: "sam@demo" },
      suggestedFix: "npm install -D typescript@^5.8.0 --workspace packages/ui",
    },
    {
      id: "f-011",
      dependency: "pytest",
      fromPackage: "services/ml",
      ecosystem: "python",
      type: "unnecessary_dependency",
      severity: "LOW",
      reasoning:
        "Test-only dependency declared in the runtime requirements file instead of the dev requirements.",
      evidence: ["services/ml/requirements.txt", "services/ml/requirements-dev.txt"],
      introducedCommit: { hash: "5b0ce2", date: "2026-07-30", author: "lena@demo" },
      suggestedFix: "move pytest to requirements-dev.txt",
    },
    {
      id: "f-012",
      dependency: "zod",
      fromPackage: "packages/app",
      ecosystem: "node",
      type: "version_drift",
      severity: "MEDIUM",
      expectedVersion: "^3.24.0",
      actualVersion: "3.22.4",
      reasoning:
        "The installed version is below the declared minimum, so newly used schema APIs are missing at runtime.",
      evidence: ["packages/app/package.json", "package-lock.json"],
      introducedCommit: { hash: "b62f80", date: "2026-08-05", author: "sam@demo" },
      suggestedFix: "npm install zod@^3.24.0 --workspace packages/app",
    },
  ],
  graph: {
    nodes: [
      {
        id: "packages/app",
        label: "packages/app",
        ecosystem: "node",
        kind: "workspace",
        status: "missing",
        version: "1.4.0",
        position: { x: 40, y: 40 },
      },
      {
        id: "packages/ui",
        label: "packages/ui",
        ecosystem: "node",
        kind: "workspace",
        status: "conflict",
        version: "0.9.2",
        position: { x: 40, y: 260 },
      },
      {
        id: "services/ml",
        label: "services/ml",
        ecosystem: "python",
        kind: "workspace",
        status: "missing",
        version: "0.3.1",
        position: { x: 40, y: 470 },
      },
      {
        id: "@demo/utils",
        label: "@demo/utils",
        ecosystem: "node",
        kind: "package",
        status: "missing",
        version: "workspace:*",
        position: { x: 360, y: 20 },
      },
      {
        id: "lodash",
        label: "lodash",
        ecosystem: "node",
        kind: "dependency",
        status: "conflict",
        version: "4.17.21",
        position: { x: 360, y: 150 },
      },
      {
        id: "axios",
        label: "axios",
        ecosystem: "node",
        kind: "dependency",
        status: "missing",
        version: "—",
        position: { x: 360, y: 280 },
      },
      {
        id: "moment",
        label: "moment",
        ecosystem: "node",
        kind: "dependency",
        status: "unused",
        version: "2.30.1",
        position: { x: 360, y: 400 },
      },
      {
        id: "numpy",
        label: "numpy",
        ecosystem: "python",
        kind: "dependency",
        status: "missing",
        version: "—",
        position: { x: 360, y: 520 },
      },
      {
        id: "flask",
        label: "flask",
        ecosystem: "python",
        kind: "dependency",
        status: "unused",
        version: "3.0.3",
        position: { x: 360, y: 640 },
      },
      {
        id: "requests",
        label: "requests",
        ecosystem: "python",
        kind: "dependency",
        status: "missing",
        version: "—",
        position: { x: 680, y: 560 },
      },
      {
        id: "urllib3",
        label: "urllib3",
        ecosystem: "python",
        kind: "dependency",
        status: "conflict",
        version: "2.2.2",
        position: { x: 680, y: 680 },
      },
    ],
    edges: [
      {
        id: "e1",
        source: "packages/app",
        target: "@demo/utils",
        state: "missing",
        label: "undeclared",
      },
      { id: "e2", source: "packages/app", target: "lodash", state: "conflict", label: "^4.17.0" },
      { id: "e3", source: "packages/app", target: "axios", state: "missing", label: "imported" },
      { id: "e4", source: "packages/ui", target: "lodash", state: "conflict", label: "^3.0.0" },
      { id: "e5", source: "packages/ui", target: "moment", state: "declared", label: "unused" },
      { id: "e6", source: "services/ml", target: "numpy", state: "missing", label: "imported" },
      { id: "e7", source: "services/ml", target: "flask", state: "declared", label: "3.0.3" },
      { id: "e8", source: "services/ml", target: "requests", state: "missing", label: "transitive" },
      { id: "e9", source: "requests", target: "urllib3", state: "conflict", label: "<2.0" },
      { id: "e10", source: "@demo/utils", target: "lodash", state: "declared", label: "^4.17.0" },
    ],
  },
  history: [
    {
      hash: "1c4e05",
      date: "2026-06-14",
      author: "sam@demo",
      message: "chore: initial workspace setup",
      dependencyChange: "Baseline manifest — 24 dependencies declared",
      driftIntroduced: false,
      files: ["package.json"],
    },
    {
      hash: "5b0ce2",
      date: "2026-07-30",
      author: "lena@demo",
      message: "chore: scaffold ml service",
      dependencyChange: "+flask 3.0.3, +pytest 8.3.2 in requirements.txt",
      driftIntroduced: true,
      severity: "LOW",
      files: ["services/ml/requirements.txt"],
      findingIds: ["f-004", "f-011"],
    },
    {
      hash: "b62f80",
      date: "2026-08-05",
      author: "sam@demo",
      message: "build: pin toolchain",
      dependencyChange: "typescript ^5.8.0 → ^5.4.2 in packages/ui",
      driftIntroduced: true,
      severity: "MEDIUM",
      files: ["packages/ui/package.json", "package-lock.json"],
      findingIds: ["f-010", "f-012"],
    },
    {
      hash: "77aa12",
      date: "2026-08-12",
      author: "priya@demo",
      message: "refactor: extract utils",
      dependencyChange: "@demo/utils imported without workspace declaration",
      driftIntroduced: true,
      severity: "HIGH",
      files: ["packages/app/src/index.ts"],
      findingIds: ["f-006"],
    },
    {
      hash: "a90f31",
      date: "2026-08-18",
      author: "lena@demo",
      message: "feat: vectorized scoring",
      dependencyChange: "numpy imported in main.py, requirements unchanged",
      driftIntroduced: true,
      severity: "HIGH",
      files: ["services/ml/main.py"],
      findingIds: ["f-003"],
    },
    {
      hash: "c14d70",
      date: "2026-08-21",
      author: "marco@demo",
      message: "feat: add http client",
      dependencyChange: "axios imported in packages/app, not declared",
      driftIntroduced: true,
      severity: "MEDIUM",
      files: ["packages/app/src/api/client.ts"],
      findingIds: ["f-002"],
    },
    {
      hash: "d31b48",
      date: "2026-08-27",
      author: "marco@demo",
      message: "chore: refresh lockfile",
      dependencyChange: "urllib3 1.26.19 → 2.2.2 (outside declared range)",
      driftIntroduced: true,
      severity: "HIGH",
      files: ["services/api/poetry.lock"],
      findingIds: ["f-005", "f-008"],
    },
    {
      hash: "8f21a9",
      date: "2026-08-29",
      author: "priya@demo",
      message: "chore: bump utility deps",
      dependencyChange: "lodash ^4.17.0 vs ^3.0.0 across workspaces",
      driftIntroduced: true,
      severity: "HIGH",
      files: ["package.json", "package-lock.json", "packages/ui/package.json"],
      findingIds: ["f-001", "f-007"],
    },
  ],
};

const monorepo: DepDriftReport = {
  version: "0.4.0",
  repository: {
    name: "test-fixtures/monorepo",
    source: "tools/depdrift/test-fixtures/monorepo",
    branch: "main",
    scannedAt: "2026-08-29T09:12:00Z",
    ecosystems: ["node"],
  },
  findings: [
    {
      id: "m-001",
      dependency: "@demo/utils",
      fromPackage: "@demo/app",
      ecosystem: "node",
      type: "missing_dependency",
      severity: "HIGH",
      reasoning:
        "`@demo/utils` is imported from the @demo/app entrypoint but is not listed in its package.json dependencies.",
      evidence: ["packages/app/src/index.js", "packages/app/package.json"],
      introducedCommit: {
        hash: "3ac901",
        date: "2026-08-22",
        author: "priya@demo",
        message: "feat: share helpers",
      },
      suggestedFix: 'npm pkg set dependencies.@demo/utils="workspace:*" --workspace @demo/app',
    },
    {
      id: "m-002",
      dependency: "chalk",
      fromPackage: "@demo/utils",
      ecosystem: "node",
      type: "unnecessary_dependency",
      severity: "LOW",
      actualVersion: "5.3.0",
      reasoning: "Declared but unreferenced across the workspace source tree.",
      evidence: ["packages/utils/package.json"],
      introducedCommit: { hash: "0be442", date: "2026-08-02", author: "sam@demo" },
      suggestedFix: "npm uninstall chalk --workspace @demo/utils",
    },
    {
      id: "m-003",
      dependency: "express",
      fromPackage: "@demo/app",
      ecosystem: "node",
      type: "version_drift",
      severity: "MEDIUM",
      expectedVersion: "^4.19.0",
      actualVersion: "4.18.2",
      reasoning: "Lockfile resolves below the declared minimum range.",
      evidence: ["packages/app/package.json", "package-lock.json"],
      introducedCommit: { hash: "3ac901", date: "2026-08-22", author: "priya@demo" },
      suggestedFix: "npm install express@^4.19.0 --workspace @demo/app",
    },
  ],
  graph: {
    nodes: [
      {
        id: "@demo/app",
        label: "@demo/app",
        ecosystem: "node",
        kind: "workspace",
        status: "missing",
        version: "1.0.0",
        position: { x: 40, y: 80 },
      },
      {
        id: "@demo/utils",
        label: "@demo/utils",
        ecosystem: "node",
        kind: "package",
        status: "missing",
        version: "1.0.0",
        position: { x: 380, y: 40 },
      },
      {
        id: "express",
        label: "express",
        ecosystem: "node",
        kind: "dependency",
        status: "conflict",
        version: "4.18.2",
        position: { x: 380, y: 180 },
      },
      {
        id: "chalk",
        label: "chalk",
        ecosystem: "node",
        kind: "dependency",
        status: "unused",
        version: "5.3.0",
        position: { x: 700, y: 40 },
      },
    ],
    edges: [
      {
        id: "me1",
        source: "@demo/app",
        target: "@demo/utils",
        state: "missing",
        label: "undeclared",
      },
      { id: "me2", source: "@demo/app", target: "express", state: "conflict", label: "^4.19.0" },
      { id: "me3", source: "@demo/utils", target: "chalk", state: "declared", label: "unused" },
    ],
  },
  history: [
    {
      hash: "0be442",
      date: "2026-08-02",
      author: "sam@demo",
      message: "chore: bootstrap workspaces",
      dependencyChange: "Baseline — 2 workspaces created",
      driftIntroduced: false,
    },
    {
      hash: "3ac901",
      date: "2026-08-22",
      author: "priya@demo",
      message: "feat: share helpers",
      dependencyChange: "@demo/utils imported without declaration",
      driftIntroduced: true,
      severity: "HIGH",
      findingIds: ["m-001", "m-003"],
      files: ["packages/app/src/index.js"],
    },
  ],
};

const python: DepDriftReport = {
  version: "0.4.0",
  repository: {
    name: "test-fixtures/python",
    source: "tools/depdrift/test-fixtures/python",
    branch: "main",
    scannedAt: "2026-08-29T09:20:00Z",
    ecosystems: ["python"],
  },
  findings: [
    {
      id: "p-001",
      dependency: "numpy",
      fromPackage: "app",
      ecosystem: "python",
      type: "missing_dependency",
      severity: "HIGH",
      reasoning: "`numpy` is imported in main.py but missing from requirements.txt.",
      evidence: ["main.py", "requirements.txt"],
      introducedCommit: {
        hash: "e11c73",
        date: "2026-08-25",
        author: "lena@demo",
        message: "feat: matrix ops",
      },
      suggestedFix: "pip install numpy==2.1.0",
    },
    {
      id: "p-002",
      dependency: "flask",
      fromPackage: "app",
      ecosystem: "python",
      type: "unnecessary_dependency",
      severity: "LOW",
      actualVersion: "3.0.3",
      reasoning: "Declared in requirements.txt with no import anywhere in the package.",
      evidence: ["requirements.txt"],
      introducedCommit: { hash: "9d0a10", date: "2026-07-11", author: "lena@demo" },
      suggestedFix: "pip uninstall flask && remove from requirements.txt",
    },
    {
      id: "p-003",
      dependency: "requests",
      fromPackage: "app",
      ecosystem: "python",
      type: "version_drift",
      severity: "MEDIUM",
      expectedVersion: ">=2.31",
      actualVersion: "2.28.1",
      reasoning: "Installed version is older than the declared constraint.",
      evidence: ["requirements.txt", "pip-freeze.txt"],
      introducedCommit: { hash: "e11c73", date: "2026-08-25", author: "lena@demo" },
      suggestedFix: "pip install 'requests>=2.31'",
    },
  ],
  graph: {
    nodes: [
      {
        id: "app",
        label: "app",
        ecosystem: "python",
        kind: "workspace",
        status: "missing",
        version: "0.1.0",
        position: { x: 40, y: 120 },
      },
      {
        id: "numpy",
        label: "numpy",
        ecosystem: "python",
        kind: "dependency",
        status: "missing",
        version: "—",
        position: { x: 380, y: 30 },
      },
      {
        id: "flask",
        label: "flask",
        ecosystem: "python",
        kind: "dependency",
        status: "unused",
        version: "3.0.3",
        position: { x: 380, y: 170 },
      },
      {
        id: "requests",
        label: "requests",
        ecosystem: "python",
        kind: "dependency",
        status: "conflict",
        version: "2.28.1",
        position: { x: 380, y: 300 },
      },
    ],
    edges: [
      { id: "pe1", source: "app", target: "numpy", state: "missing", label: "imported" },
      { id: "pe2", source: "app", target: "flask", state: "declared", label: "unused" },
      { id: "pe3", source: "app", target: "requests", state: "conflict", label: ">=2.31" },
    ],
  },
  history: [
    {
      hash: "9d0a10",
      date: "2026-07-11",
      author: "lena@demo",
      message: "chore: initial service",
      dependencyChange: "Baseline — flask, requests declared",
      driftIntroduced: false,
    },
    {
      hash: "e11c73",
      date: "2026-08-25",
      author: "lena@demo",
      message: "feat: matrix ops",
      dependencyChange: "numpy imported, requirements.txt unchanged",
      driftIntroduced: true,
      severity: "HIGH",
      findingIds: ["p-001", "p-003"],
      files: ["main.py"],
    },
  ],
};

const conflict: DepDriftReport = {
  version: "0.4.0",
  repository: {
    name: "test-fixtures/conflict",
    source: "tools/depdrift/test-fixtures/conflict",
    branch: "main",
    scannedAt: "2026-08-29T09:33:00Z",
    ecosystems: ["node"],
  },
  findings: [
    {
      id: "c-001",
      dependency: "lodash",
      fromPackage: "packages/app",
      ecosystem: "node",
      type: "version_conflict",
      severity: "HIGH",
      expectedVersion: "^4.17.0",
      actualVersion: "^3.0.0",
      reasoning:
        "Cross-package version conflict: packages/app requires lodash ^4.17.0 while packages/ui pins ^3.0.0.",
      evidence: ["packages/app/package.json", "packages/ui/package.json", "package-lock.json"],
      introducedCommit: {
        hash: "4fd7c2",
        date: "2026-08-28",
        author: "sam@demo",
        message: "fix: pin legacy lodash in ui",
      },
      suggestedFix: "npm install lodash@^4.17.0 --workspace packages/ui",
    },
    {
      id: "c-002",
      dependency: "lodash",
      fromPackage: "packages/ui",
      ecosystem: "node",
      type: "version_drift",
      severity: "MEDIUM",
      expectedVersion: "^3.0.0",
      actualVersion: "3.10.1",
      reasoning: "Legacy major resolved in a duplicated tree, doubling bundle size.",
      evidence: ["packages/ui/package.json", "package-lock.json"],
      introducedCommit: { hash: "4fd7c2", date: "2026-08-28", author: "sam@demo" },
      suggestedFix: "npm dedupe",
    },
  ],
  graph: {
    nodes: [
      {
        id: "packages/app",
        label: "packages/app",
        ecosystem: "node",
        kind: "workspace",
        status: "conflict",
        version: "2.1.0",
        position: { x: 40, y: 40 },
      },
      {
        id: "packages/ui",
        label: "packages/ui",
        ecosystem: "node",
        kind: "workspace",
        status: "conflict",
        version: "1.6.0",
        position: { x: 40, y: 240 },
      },
      {
        id: "lodash@4",
        label: "lodash ^4.17.0",
        ecosystem: "node",
        kind: "dependency",
        status: "conflict",
        version: "4.17.21",
        position: { x: 400, y: 40 },
      },
      {
        id: "lodash@3",
        label: "lodash ^3.0.0",
        ecosystem: "node",
        kind: "dependency",
        status: "conflict",
        version: "3.10.1",
        position: { x: 400, y: 240 },
      },
    ],
    edges: [
      {
        id: "ce1",
        source: "packages/app",
        target: "lodash@4",
        state: "conflict",
        label: "^4.17.0",
      },
      { id: "ce2", source: "packages/ui", target: "lodash@3", state: "conflict", label: "^3.0.0" },
    ],
  },
  history: [
    {
      hash: "20b6ea",
      date: "2026-08-10",
      author: "priya@demo",
      message: "chore: baseline",
      dependencyChange: "lodash ^4.17.0 declared in both packages",
      driftIntroduced: false,
    },
    {
      hash: "4fd7c2",
      date: "2026-08-28",
      author: "sam@demo",
      message: "fix: pin legacy lodash in ui",
      dependencyChange: "packages/ui lodash ^4.17.0 → ^3.0.0",
      driftIntroduced: true,
      severity: "HIGH",
      findingIds: ["c-001", "c-002"],
      files: ["packages/ui/package.json"],
    },
  ],
};

export const MOCK_REPORTS: Record<FixtureId, DepDriftReport> = {
  polyglot,
  monorepo,
  python,
  conflict,
};
